def DNA(s):
  a = c = g = t = 0
  for ch in s:
    if (ch == 'A'):
      a += 1
    if (ch == 'C'):
      c += 1
    if (ch == 'G'):
      g += 1
    if (ch == 'T'):
      t += 1
  print a, c, g, t

DNA("GTCGTGGGGAGATTAGAAGGCGGGCGTGGGATCAACAAATTACTGCATTCTGTCAGGCTGGGACTTCACGGGAGGCATTACGAATCTGGTTGCTGAAGCGATGATCAAGTACGCAAAAAGCCGACAAAGGGGGAGTTAACCCGCTGCTAGCTTGATAACTTAGAGCGGGCCTCGGGGATAACCAATTCCTTCGTAAGCGCGGCGGCTGTGCTGTTGTTATAGCCTGACTTGCACTCTGAGGAGACGGTGGCTGCTTACCTAGAATCAATGGGAAGTGATGAGCCAAAACCCGATAGCTGACCTTTTCTTTTACTTCACAACGACGCTTTCAACGGTTCTGTAATGTTCAGCCCGCCTCTGGAGAAGATTTGTGGTCCTTTGTAGCGTCGTATGTAGCCTTTACGATCAGCTACCCGGGGCCGGGCAGACAAAAAGCTGCTTATGTGTTTACCTTGCTAAAGTAAGTCCCCTAGCTAAACGTTACTAACTTCGCATGTGGGTGGTGCCCAATCGCTTGGCTTACTTTATCCTTTTCCCGCTACGTCAGCCAAGATGCATTATTCAAGCCGATACCTACTTCGCGGAAACGTTGCCTCCAATACCTTGTTAGAGTTATGGCTAGTGCCCCTCCCCCAGCTTCGACTGCGGAAACAGCCGGTTCAAGCCGTTAATTCTCAATTGACAGCGGGACGGTAGTGCGGACGCCTTCAGTGGAGATCTATTAGAGACACGACTTATACTCTAATCCAGATCGTTACACCAGCTGGAGTGGACTAGTAGTCATCACTAGCTGAGAGCCCTACTTGGGCTACTGGCATTCTAAACCAGCGCAGCGGTTAACAATGCGCGGAAAGGAGACG")
