def reverse_complement(s):
  result = ""
  for c in s:
    result = complement(c) + result
  return result

def complement(c):
    if (c == 'A'):
      return 'T'
    if (c ==  'T'):
      return 'A'
    if (c == 'G'):
      return 'C'
    if (c == 'C'):
      return 'G'

print reverse_complement("TAGAGTGTTCGGTGGACCTTCCGTCAGGAAACCCTGCTTAGGGGACGTACGCTCGCGTACTCCCGAAAGGTCGGCGAAAAGGCAACACCTACTCGATTGCCACATCCACGGCACCACACCATGTCCGACAGGAGGAACCAGCATTCGGGATCTACTACTGGAGCACCAGCTCCCTCGTACCCAGCGACAGCTGAGCATGGTTACGGACCCCAGTCTGCATCCTGCGATATGCGAGAGATATAGTGACTATAGAACTGGCGTATATCGGCAGAACACCCCCAGACGGAAATAGATGTTTGCGTCTGGAGTGTACGGCGTCAATCCCTCGCTTGATAATATCGCCGGGAAAAATGGATGGGACTATATCTCATCCACGAACAGGTTACGGCAACATCCGACATCGGGATAACTAACGCTTGACTGCACGCCCAACAAGACGCCAAAGTAGAGCTGCACTAGCTCCGGCGACCAATCAGAGTCGACCAAGCCCCATCTCTGGACGCGTGTGATGTACAATGGAGTTAATGAGACTCGTTCGCTGAAAAAGGCACGCACAATGGACATATATCCCCAGCCAGGGGTGTATTTTCTGCGTACCATAGACGTAGGTGATTTGACTTGGCACATCCCACCTGAAAATTAATAGATTTCAGCTTTTATCCTGCATAGTAACGCGTTCTGCGTGATACTTTCTTGTATCCCCCCGCGAAAAGCCCCTTCTCAACCATCACGTATACCGGGGAACGCATGACTAGTCCCCTGGTGAGAGGGTATTCTAACTACTAGTTTTGTCGTTATAAGCAGTAGTGGATGCCGGACTAGGCAGGACTTTTGAATATATAAGCGAAAAGATGAGATGCAATTCATTATTCTATCATGTGCCGACCACGTT")
